name: remote ssh command
on: 
  push:

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.WEB_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.WEB_PORT }}
          script: |
            cd /root 
            bash ./deploy_project_ext.sh ${{ github.event.repository.name }} /home/ermwhatthesigma.me/public_html "npm install" "npm run build"
